# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-11 02:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_auto_20180708_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0, help_text='余额')),
                ('userinfo', models.OneToOneField(help_text='用户信息', on_delete=django.db.models.deletion.CASCADE, to='questionnaire.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='PointHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True, help_text='发生时间')),
                ('quantity', models.IntegerField(default=0, help_text='数量')),
                ('reason', models.CharField(help_text='变动原因', max_length=32)),
                ('direction', models.BooleanField(default=True, help_text='减少为False，增加为True')),
                ('point', models.ForeignKey(help_text='积分历史', on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Point')),
            ],
        ),
    ]
