# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-11 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_wallet_walletflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletflow',
            name='wallet',
            field=models.ForeignKey(help_text='钱包', on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Wallet'),
        ),
    ]
