# Generated by Django 2.0.7 on 2018-07-13 01:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0005_auto_20180711_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='questionnaire',
            field=models.ForeignKey(on_delete=True, to='questionnaire.Questionnaire'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='userinfo',
            field=models.ForeignKey(on_delete=True, to='questionnaire.UserInfo'),
        ),
        migrations.AlterField(
            model_name='answeritem',
            name='item',
            field=models.ForeignKey(help_text='选项', on_delete=True, to='questionnaire.QuestionItem'),
        ),
        migrations.AlterField(
            model_name='answeritem',
            name='userinfo',
            field=models.ForeignKey(help_text='用户信息', null=True, on_delete=True, to='questionnaire.UserInfo'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='point',
            name='userinfo',
            field=models.OneToOneField(help_text='用户信息', on_delete=True, to='questionnaire.UserInfo'),
        ),
        migrations.AlterField(
            model_name='pointhistory',
            name='point',
            field=models.ForeignKey(help_text='积分历史', on_delete=True, to='questionnaire.Point'),
        ),
        migrations.AlterField(
            model_name='question',
            name='questionnaire',
            field=models.ForeignKey(on_delete=True, to='questionnaire.Questionnaire'),
        ),
        migrations.AlterField(
            model_name='questionitem',
            name='question',
            field=models.ForeignKey(on_delete=True, to='questionnaire.Question'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='customer',
            field=models.ForeignKey(on_delete=True, to='questionnaire.Customer'),
        ),
        migrations.AlterField(
            model_name='questionnairecomment',
            name='questionnaire',
            field=models.ForeignKey(on_delete=True, to='questionnaire.Questionnaire'),
        ),
        migrations.AlterField(
            model_name='questionnairesuggest',
            name='questionnaire',
            field=models.ForeignKey(on_delete=True, to='questionnaire.Questionnaire'),
        ),
        migrations.AlterField(
            model_name='questionnairesuggest',
            name='userinfo',
            field=models.ForeignKey(null=True, on_delete=True, to='questionnaire.UserInfo'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user',
            field=models.OneToOneField(on_delete=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='customer',
            field=models.OneToOneField(help_text='客户', on_delete=True, to='questionnaire.Customer'),
        ),
        migrations.AlterField(
            model_name='walletflow',
            name='wallet',
            field=models.ForeignKey(help_text='钱包', on_delete=True, to='questionnaire.Wallet'),
        ),
    ]
